project:
  type: website
  execute-dir: project
  resources: scripts
site-url: https://sussmanbu.github.io/ma4615-fa23-final-project-group-7/

website:
  title: "MA [46]15 Final Project - Group 7"
  navbar:
    right:
      - about.qmd
      - big_picture.qmd
      - analysis.qmd
      - data.qmd
format:
  html:
    theme: cosmo
    css: styles.css



