---
title: "Other datasets"
author: ""
subtitle: ""
description:  |
  Blog post describing other datasets we found and our initial thoughts to combine them.
date: "2024-11-11"
date-modified: "2024-11-11"
draft: FALSE
---

Dataset:
[Police Sentiment Survey](https://data.tempe.gov/datasets/tempegov::police-sentiment-survey-detail-1/about)

**Description**
The Tempe Police Sentiment Survey dataset captures detailed perceptions of safety and trust in the Tempe community, categorized by demographics such as race, age, gender, education, and income levels. Also, data is catagorized by different geographical areas within Tempe, including patrol zones and beats. The metrics include community members' feelings of safety and levels of trust and respect towards the police. Responses are broken down further to reflect sentiments within specific demographic groups, covering general and respect-focused trust levels. Each record includes start and end dates for when the survey data was collected, providing a time-based context for analyzing sentiment changes over time.
The weakness of the dataset is that the data does not align with our original dataset. Our original dataset's date is from 2002-2011, and this dataset is more recent, with data afte 2020. We're not sure if this works.

**Combination**
We haven't started to combine the dataset yet, but we have some initial thoughts. For example, we can do some incident-based analysis. We can examine how specific types of police-public interactions (e.g., arrests, traffic stops) affect sentiment. We can match by incident identifiers and by combining incidents from both datasets, we can analyze whether particular types of police interactions correlate with higher or lower levels of trust and safety sentiments within specific demographics or locations. Also, this dataset includes many socioeconomic factors such as race, education level, income, and age, etc. We can also take these factors into account.

<<<<<<< HEAD
Dataset:
[State-Level Household Gun Ownership Proxy Dataset](https://pmc.ncbi.nlm.nih.gov/articles/PMC10514438/)
=======
Dataset 2: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/QVYDUD, 

Description of the Dataset:
This dataset describes the number of homocides, the number of suicides, and the number of suicides done with firearms for whites & nonwhites within different states from 1949 to 2020. These numbers, particularly the FSS (the ratio of the number of suicides done with firearms/the total number of suicides) is used as a much less biased estimator of the total gun ownership in the US than traditional voluntary surveys, in which people underestimate the number of guns they own out of social desirability bias. Advantages of linking this particular dataset include the overlap of the demographics, state variables, and time as well as a probable connection between gun ownership and crime prevalence within communities. Luckily, this dataset has few missing values and the time periods analyzed closely correspond to those in our original dataset.
Nevertheless, if used, we anticipate some problems. One problem arises from the fact that the demographic data is only split between whites and non-whites, which may prevent us from understanding the true role of demographics on police reporting data. Another problem arises from the fact that FSS is used as an estimate of gun ownership rates instead of definite numbers of guns per person/household. A separate dataset might need to be used to link FSS to gun ownership rates.

Combination of the dataset:
Although we haven't started to combine the dataset, we plan on observing whether there exists a correlation between FSS (which correlates with the number of guns per capita) and crime reporting prevalence in various communities. We would expect a positive correlation, but confounding variables (demographics, safety, etc.) may make the correlation less obvious. We also plan on analyzing the differences between the FSS of whites and non-whites within different states and whether that correlates with the number of crimes reported by separate demographics. Finally, we plan on determining whether a correlation can be observed between homocide rate and general crime rate in different states.
>>>>>>> fa0f35daaaa3ace4f9b1cc801ac8578aeafa48c8

**Description**
This dataset holds the count and population-adjusted rate of suicides, firearm suicides, homicides, and firearm homicides, among other figures. In general it was created by extending an existing proxy for U.S. household gun ownership rates. Most importantly this data was not compiled from self-reporting data, which can be heavily skewed based on the bias of those who choose to report. This extended proxy represents the most comprehensive report of state-level gun ownership rates and trends.

**Combination**
We wanted to check if this dataset would be compatible with our previous dataset. In terms of combining them into a its own study we would look to see how the gun-ownership of individuals may affect their view on their interactions with the police. In doing so we can see if those individuals in higher gun ownership states are more comfortable or apprehensive in their interactions with law enforcement. In the same affect we can see if the presence of a gun owner changes the way that law enforcement approach interactions with the public. In doing a more detailed analysis we can see if gun ownership improves the relationship of law enforcement and those they serve and protect. 

Furthermore we may also see how trends in gun ownership across time correlate to patterns in the original survey we studied. This can be used in comprehension with regional changes to better study any pattern that may exist. Having multiple means of doing so would reduce the likelihood of chance being the root cause of any patterns.
