---
title: "Data Background"
author: ""
subtitle: ""
description:  |
  Blog post outlining background information related to our dataset.
date: "2024-10-15"
date-modified: "2024-10-15"
draft: FALSE
---

Dataset Name: The Effect of Prior Police Contact on Victimization Reporting: Results From the Police-Public Contact and National Crime Victimization Surveys, United States, 2002-2011 (ICPSR 36370) [Dataset Link](https://www.icpsr.umich.edu/web/NACJD/studies/36370/)

**"Where does the data come from?" - Arjun**

The data in this dataset is compiled from the National Crime Victimization Survey (NCVS) and the Police-Public Contact Survey (PPCS). The NCVS is a annual survey of approximately 240,000 people in 150,000 US households which reports background information of the person being surveyed, the number and type of crimes each person was victimized by within the past year, and background information of any offenders. Also reported is the reason why/why not the crime was reported to police and the victim's experience in the criminal justice system. Meanwhile, the PPCS is a supplement survey to the NCVS which documents characteristics of people who had any contact with police in the previous year. During the time period represented by data in this dataset, the PPCS was conducted approximately every 3 years. The dataset was formed by merging the NCVS and PPCS data from 2002, 2008, and 2011. In those years, 76,910, 57,978, and 49,246 people took part in both the NCVS and PPCS, respectively. After filtering, data of police contact and victimization experiences within the previous year for 105,273 people aged 16 or older in the US is included.

Sources (idk if we need to cite) https://bjs.ojp.gov/programs/ncvs https://bjs.ojp.gov/data-collection/police-public-contact-survey-ppcs

**"Who collected it?" - Arjun**

The original, raw data used to compile the data in this dataset comes from the National Crime Victimization Survey (NCVS) and the Police-Public Contact Survey (PPCS). Both are collected by the Bureau of Justice Statistics (BJS), which is the primary statistical agency of the US's Department of Justice. It was first established in 1979 in order to better understand statistics about crimes in the United States.

[Source](https://bjs.ojp.gov/about)

**"Why was it collected?"**

The reason why this data was collected was to delve into how prior individual and vicarious experiences of law enforcement play a role when individuals have to make decisions on reporting crime or not. In this approach, utilizing the National Crime Victimization Survey (NCVS) data alongside the Police-Public Contact Survey (PPCS) data, the researchers believed that they will explore the understanding of the causes of crime reporting among individuals with such study population. It is still a question, for example, whether such additional factors as the amount and nature of encounters with the police—good or bad—during the life of a person contributed to his or her confidence in, and willingness to assist, law enforcement personnel when they themselves have become victims of crime. Social and psychological aspects of engaging the enforcement agents and in particular the demographic factors such as age, race, sex, and social class were assumed to be included in order to find out if these various demographic factors aid in or inhibit crime reporting whenever police is encountered, thus shedding light on the concerns of uneven treatment of particular groups by the law.

**"Are you able to find the data from the original source?"** 
Yes, the data was collected from the NCVS and PPCS surveys taht were linked in this source. 

"Are there any issues you can see with how the data was collected?"
Issues with how the data was collected: Variables common to the NCVS and PPCS were concatenated to create unique identifiers which could link the two datasets, but there was variation in how much the data had to be manipulated to create them.
Another issue is with the weights:  not all PPCS interviews could be matched, therefore population estimates are not necessarily representative of the U.S. population.
The sample population is 105,273 people ages 16 and older living in the United States.

**"Are there reasons to think the sample is biased in some way?"**

Due to the means that the dataset was collected, the dataset is susceptible to inherit bias found in the sample that is collected. The dataset relies on matching responses to the PPCS (Public-Police Contact Survey) to corresponding responses in the NCVS (National Crime Victimization Survey). Since this dataet relies on responses to both of these surveys it is possible that the sample is biased in that individuals who experienced victimization at the hand of law enforcement may be more likely to respond to the NCVS versus those who may not have. This could lead to some statistics being displayed inaccurately in relation to the entire population as a whole.

**"How is this data used? Has there been other research on the same data?"**

The dataset is used to examine whether or not there is a relation between the presence of face-to-face interactions with law enforcement, and subsequent reports of victimizations. It also helps to outline the general prior police conduct made with individuals who identify as victims and those who do not. 

Outside of the original paper published in correspondence with the dataset itself, we could not find any other publications which site this set. While we were unable to find any other studies using this data, it is certainly possible that there are other groups/individuals who are using this dataset for their own studies. 

<<<<<<< HEAD
"Is this data being used for some policy decisions?"
The dataset provides detailed crime data in the U.S. and is used in policy-making decisions. Law enforcement agencies, policymakers, and researchers use NIBRS data to identify crime trends, allocate resources, and develop crime prevention strategies. 

"What questions have others asked about this data?"

How can the data be used to assess the impact of local or national policy changes? How do different types of crimes (e.g., property crimes, violent crimes) vary by time of year, geography, or demographic group? 

**"Is this data being used for some policy decisions?"**
The dataset provides detailed crime data in the U.S. and is used in policy-making decisions. Law enforcement agencies, policymakers, and researchers use NIBRS data to identify crime trends, allocate resources, and develop crime prevention strategies. 


**"What questions have others asked about this data?"**
How can the data be used to assess the impact of local or national policy changes? How do different types of crimes (e.g., property crimes, violent crimes) vary by time of year, geography, or demographic group? 

